In [11]:
!python test.py --backbone mobilenet_v2 --label_path="F:\Minor Project\Monument Object Detection\helper\Report\ps-up-sp-BDS-alamy-merged.csv"

2023-01-27 18:19:25.292904: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-01-27 18:19:25.292970: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-01-27 18:19:33.220513: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2023-01-27 18:19:33.220545: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2023-01-27 18:19:33.224824: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: Proghosta
2023-01-27 18:19:33.224944: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: Proghosta
2023-01-27 18:19:33.225557: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized w

In [12]:
import tensorflow as tf
from utils import bbox_utils, data_utils, drawing_utils, io_utils, train_utils, eval_utils
from models.decoder import get_decoder_model
from helper import label_generator
from models.ssd_mobilenet_v2 import get_model, init_model

In [16]:
hyper_params = train_utils.get_hyper_params('mobilenet_v2')

labels = label_generator.csv_to_label_map("F:\Minor Project\Monument Object Detection\helper\Report\ps-up-sp-BDS-alamy-merged.csv", 'list-type')
labels = ["bg"] + labels
hyper_params["total_labels"] = len(labels)
img_size = hyper_params["img_size"]

data_types = data_utils.get_data_types()
data_shapes = data_utils.get_data_shapes()
padding_values = data_utils.get_padding_values()


ssd_model = get_model(hyper_params)
ssd_model_path = io_utils.get_model_path('mobilenet_v2')
ssd_model.load_weights(ssd_model_path)


prior_boxes = bbox_utils.generate_prior_boxes(hyper_params["feature_map_shapes"], hyper_params["aspect_ratios"])
ssd_decoder_model = get_decoder_model(ssd_model, prior_boxes, hyper_params)

In [25]:
from PIL import Image
import numpy as np
image = Image.open('./1506.JPG')

In [33]:
np_image = np.asarray(image)
np_image = np.expand_dims(np_image, axis = 0)
print(np_image)
ssd_decoder_model.predict(np_image)

[[[[  4   4   4]
   [  4   4   4]
   [  4   4   4]
   ...
   [ 89 166 254]
   [ 89 166 254]
   [ 89 166 254]]

  [[  4   4   4]
   [  4   4   4]
   [  4   4   4]
   ...
   [ 89 166 254]
   [ 89 166 254]
   [ 89 166 254]]

  [[  4   4   4]
   [  4   4   4]
   [  4   4   4]
   ...
   [ 89 166 254]
   [ 89 166 254]
   [ 89 166 254]]

  ...

  [[190 154 142]
   [149 127 114]
   [161 157 148]
   ...
   [ 11  11  11]
   [ 14  14  14]
   [ 19  19  19]]

  [[174 145 129]
   [142 120 106]
   [161 150 144]
   ...
   [ 11  11  11]
   [ 13  13  13]
   [ 18  18  18]]

  [[181 160 143]
   [150 131 117]
   [170 155 152]
   ...
   [  9   9   9]
   [ 11  11  11]
   [ 16  16  16]]]]
1/1 [==============================] - 0s 89ms/step


[array([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
 

In [3]:
!pip install roboflow

In [1]:
from roboflow import Roboflow
rf = Roboflow(api_key="OkJEjbpGzllGhCgEatqA")
project = rf.workspace().project("monument-detection")
model = project.version(1).model

loading Roboflow workspace...
loading Roboflow project...


In [3]:
print(model.predict("./test_images/2565.jpg", confidence=40, overlap=30).json())

{'predictions': [{'x': 88.5, 'y': 148.5, 'width': 129.0, 'height': 139.0, 'confidence': 0.8811545372009277, 'class': 'lalitpur tower', 'image_path': './test_images/2565.jpg', 'prediction_type': 'ObjectDetectionModel'}, {'x': 24.5, 'y': 186.5, 'width': 49.0, 'height': 73.0, 'confidence': 0.5100283026695251, 'class': 'gaddi durbar', 'image_path': './test_images/2565.jpg', 'prediction_type': 'ObjectDetectionModel'}], 'image': {'width': 300, 'height': 300}}
